#!/usr/bin/env python3
"""Utilities for validating submissions and running isolated MIT Pokerbots matches."""

from __future__ import annotations

import json
import re
import shutil
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


SUBMISSION_PATTERN = re.compile(r"^submission/([^/]+)/(python_bot|cpp_bot)(/.*)?$")
FINAL_LINE_PATTERN = re.compile(
    r"^Final,\s*(?P<p1>[^,]+)\s+\((?P<b1>-?\d+)\),\s*(?P<p2>[^,]+)\s+\((?P<b2>-?\d+)\)\s*$"
)


@dataclass
class BotSubmission:
    roll_no: str
    bot_type: str
    path: Path

    @property
    def bot_id(self) -> str:
        return f"{self.roll_no}/{self.bot_type}"


@dataclass
class ValidationResult:
    ok: bool
    errors: list[str]


@dataclass
class MatchResult:
    ok: bool
    player_1_name: str
    player_2_name: str
    player_1_bankroll: int
    player_2_bankroll: int
    log_path: Path | None
    engine_stdout: str
    failure_reason: str | None = None


def _ensure_relative_to_repo(path: Path, repo_root: Path) -> str:
    return path.resolve().relative_to(repo_root.resolve()).as_posix()


def discover_submission_bots(submissions_root: Path) -> list[BotSubmission]:
    bots: list[BotSubmission] = []
    if not submissions_root.exists():
        return bots

    for roll_dir in sorted(p for p in submissions_root.iterdir() if p.is_dir()):
        for bot_type in ("python_bot", "cpp_bot"):
            bot_dir = roll_dir / bot_type
            if bot_dir.is_dir():
                bots.append(BotSubmission(roll_no=roll_dir.name, bot_type=bot_type, path=bot_dir))
    return bots


def discover_changed_files(repo_root: Path, base_ref: str) -> list[str]:
    cmd = ["git", "diff", "--name-only", "--diff-filter=ACMR", f"{base_ref}...HEAD"]
    proc = subprocess.run(cmd, cwd=repo_root, text=True, capture_output=True, check=False)
    if proc.returncode != 0:
        raise RuntimeError(f"Unable to compute changed files: {proc.stderr.strip()}")
    return [line.strip() for line in proc.stdout.splitlines() if line.strip()]


def parse_changed_submissions(changed_files: Iterable[str]) -> tuple[list[BotSubmission], list[str]]:
    found: dict[tuple[str, str], BotSubmission] = {}
    invalid_paths: list[str] = []

    for rel_path in changed_files:
        if not rel_path.startswith("submission/"):
            continue
        match = SUBMISSION_PATTERN.match(rel_path)
        if not match:
            invalid_paths.append(rel_path)
            continue
        roll_no, bot_type = match.group(1), match.group(2)
        found[(roll_no, bot_type)] = BotSubmission(
            roll_no=roll_no,
            bot_type=bot_type,
            path=Path("submission") / roll_no / bot_type,
        )

    return sorted(found.values(), key=lambda b: (b.roll_no, b.bot_type)), sorted(invalid_paths)


def validate_submission(submission: BotSubmission, repo_root: Path) -> ValidationResult:
    errors: list[str] = []
    absolute = (repo_root / submission.path).resolve()

    if not absolute.is_dir():
        return ValidationResult(False, [f"Missing directory: {submission.path.as_posix()}"])

    commands_path = absolute / "commands.json"
    if not commands_path.exists():
        errors.append("Missing required file commands.json")
    else:
        try:
            commands = json.loads(commands_path.read_text(encoding="utf-8"))
            build_cmd = commands.get("build")
            run_cmd = commands.get("run")
            if not isinstance(build_cmd, list) or not isinstance(run_cmd, list):
                errors.append("commands.json must define list-valued keys: build and run")
            elif not run_cmd:
                errors.append("commands.json run command cannot be empty")
        except json.JSONDecodeError as exc:
            errors.append(f"commands.json is not valid JSON: {exc}")

    if submission.bot_type == "python_bot":
        if not (absolute / "player.py").exists():
            errors.append("python_bot submission must include player.py")
    elif submission.bot_type == "cpp_bot":
        cpp_indicators = [absolute / "build.sh", absolute / "Makefile", absolute / "CMakeLists.txt"]
        if not any(p.exists() for p in cpp_indicators):
            errors.append("cpp_bot must include one build indicator: build.sh, Makefile, or CMakeLists.txt")

    return ValidationResult(ok=not errors, errors=errors)


def _write_generated_config(
    dst_config: Path,
    player_1_name: str,
    player_1_path: str,
    player_2_name: str,
    player_2_path: str,
    num_rounds: int,
    game_log_filename: str,
) -> None:
    lines = [
        "# Auto-generated by scripts/tournament/tournament_utils.py",
        "PLAYER_1_NAME = {!r}".format(player_1_name),
        "PLAYER_1_PATH = {!r}".format(player_1_path),
        "PLAYER_2_NAME = {!r}".format(player_2_name),
        "PLAYER_2_PATH = {!r}".format(player_2_path),
        "GAME_LOG_FILENAME = {!r}".format(game_log_filename),
        "PLAYER_LOG_SIZE_LIMIT = 524288",
        "ENFORCE_GAME_CLOCK = True",
        "STARTING_GAME_CLOCK = 60.0",
        "BUILD_TIMEOUT = 20.0",
        "CONNECT_TIMEOUT = 20.0",
        f"NUM_ROUNDS = {num_rounds}",
        "STARTING_STACK = 400",
        "BIG_BLIND = 2",
        "SMALL_BLIND = 1",
        "ROUNDS_PER_BOUNTY = 25",
        "BOUNTY_RATIO = 1.5",
        "BOUNTY_CONSTANT = 10",
        "PLAYER_TIMEOUT = 120",
        "",
    ]
    dst_config.write_text("\n".join(lines), encoding="utf-8")


def _safe_copytree(src: Path, dst: Path) -> None:
    if src.is_dir():
        shutil.copytree(src, dst, symlinks=False)
    else:
        raise FileNotFoundError(f"Expected directory not found: {src}")


def _parse_bankrolls(game_log_path: Path, expected_p1: str, expected_p2: str) -> tuple[int, int]:
    if not game_log_path.exists():
        raise RuntimeError(f"Engine did not produce log file: {game_log_path}")

    lines = game_log_path.read_text(encoding="utf-8", errors="replace").splitlines()
    for line in reversed(lines):
        match = FINAL_LINE_PATTERN.match(line.strip())
        if not match:
            continue
        p1_name = match.group("p1").strip()
        p2_name = match.group("p2").strip()
        b1 = int(match.group("b1"))
        b2 = int(match.group("b2"))

        if (p1_name, p2_name) == (expected_p1, expected_p2):
            return b1, b2
        if (p1_name, p2_name) == (expected_p2, expected_p1):
            return b2, b1

        raise RuntimeError(
            f"Unexpected final line names: got ({p1_name}, {p2_name}), "
            f"expected ({expected_p1}, {expected_p2}) in any order"
        )

    raise RuntimeError("Could not parse final bankroll line from engine log")


def run_isolated_match(
    repo_root: Path,
    player_1_source: Path,
    player_2_source: Path,
    output_dir: Path,
    player_1_name: str,
    player_2_name: str,
    num_rounds: int,
    timeout_seconds: int = 900,
) -> MatchResult:
    output_dir.mkdir(parents=True, exist_ok=True)
    log_filename = f"gamelog_{player_1_name}_vs_{player_2_name}".replace("/", "_")

    try:
        with tempfile.TemporaryDirectory(prefix="pokerbots_match_") as temp_dir:
            sandbox = Path(temp_dir)
            engine_src = repo_root / "engine.py"
            if not engine_src.exists():
                return MatchResult(
                    ok=False,
                    player_1_name=player_1_name,
                    player_2_name=player_2_name,
                    player_1_bankroll=0,
                    player_2_bankroll=0,
                    log_path=None,
                    engine_stdout="",
                    failure_reason="engine.py not found in repository root",
                )

            shutil.copy2(engine_src, sandbox / "engine.py")

            p1_dst_rel = "player_1"
            p2_dst_rel = "player_2"
            _safe_copytree(player_1_source, sandbox / p1_dst_rel)
            _safe_copytree(player_2_source, sandbox / p2_dst_rel)

            _write_generated_config(
                dst_config=sandbox / "config.py",
                player_1_name=player_1_name,
                player_1_path=f"./{p1_dst_rel}",
                player_2_name=player_2_name,
                player_2_path=f"./{p2_dst_rel}",
                num_rounds=num_rounds,
                game_log_filename=log_filename,
            )

            proc = subprocess.run(
                ["python3", "engine.py"],
                cwd=sandbox,
                text=True,
                capture_output=True,
                timeout=timeout_seconds,
                check=False,
            )
            engine_stdout = (proc.stdout or "") + ("\n" + proc.stderr if proc.stderr else "")

            game_log_path = sandbox / f"{log_filename}.txt"
            copied_log_path: Path | None = None
            if game_log_path.exists():
                copied_log_path = output_dir / f"{log_filename}.txt"
                shutil.copy2(game_log_path, copied_log_path)

            if proc.returncode != 0:
                return MatchResult(
                    ok=False,
                    player_1_name=player_1_name,
                    player_2_name=player_2_name,
                    player_1_bankroll=0,
                    player_2_bankroll=0,
                    log_path=copied_log_path,
                    engine_stdout=engine_stdout,
                    failure_reason=f"engine.py exited with non-zero status: {proc.returncode}",
                )

            p1_bankroll, p2_bankroll = _parse_bankrolls(game_log_path, player_1_name, player_2_name)
            return MatchResult(
                ok=True,
                player_1_name=player_1_name,
                player_2_name=player_2_name,
                player_1_bankroll=p1_bankroll,
                player_2_bankroll=p2_bankroll,
                log_path=copied_log_path,
                engine_stdout=engine_stdout,
                failure_reason=None,
            )

    except subprocess.TimeoutExpired:
        return MatchResult(
            ok=False,
            player_1_name=player_1_name,
            player_2_name=player_2_name,
            player_1_bankroll=0,
            player_2_bankroll=0,
            log_path=None,
            engine_stdout="",
            failure_reason=f"Match timed out after {timeout_seconds} seconds",
        )
    except Exception as exc:  # broad catch to produce deterministic CI feedback
        return MatchResult(
            ok=False,
            player_1_name=player_1_name,
            player_2_name=player_2_name,
            player_1_bankroll=0,
            player_2_bankroll=0,
            log_path=None,
            engine_stdout="",
            failure_reason=str(exc),
        )


def make_repo_relative(path: Path, repo_root: Path) -> str:
    return _ensure_relative_to_repo(path, repo_root)
